Repository palantir/gradle-conjure, pull requests merged in 2019-10, with the labels that each got.

#252 Create .changelog.yml
  .changelog.yml
Labels: merge when ready, no changelog

#257 Don't set source dirs with immutable set
  changelog/@unreleased/pr-257.v2.yml
  gradle-conjure/src/main/java/com/palantir/gradle/conjure/ConjurePlugin.java
Labels: autorelease, merge when ready

#258 Actually don't set source sets as immutable
  changelog/@unreleased/pr-258.v2.yml
  gradle-conjure/src/main/java/com/palantir/gradle/conjure/ConjurePlugin.java
  gradle-conjure/src/test/groovy/com/palantir/gradle/conjure/ConjurePluginTest.groovy
Labels: autorelease, merge when ready

#260 Set IDEA source dirs
  changelog/@unreleased/pr-260.v2.yml
  gradle-conjure/src/main/java/com/palantir/gradle/conjure/ConjurePlugin.java
  gradle-conjure/src/test/groovy/com/palantir/gradle/conjure/ConjurePluginTest.groovy
Labels: autorelease
