Repository palantir/gradle-conjure, pull requests merged in 2020-02, with the labels that each got.

#371 Fix: Use jakarta-api instead javax-api
  changelog/@unreleased/pr-371.v2.yml
  gradle-conjure/src/main/java/com/palantir/gradle/conjure/ConjurePlugin.java
  gradle-conjure/src/test/groovy/com/palantir/gradle/conjure/ConjurePluginTest.groovy
  gradle-conjure/src/test/groovy/com/palantir/gradle/conjure/ConjureServiceDependencyTest.groovy
Labels: autorelease, merge when ready

#363 add conjure-java-local plugin
  changelog/@unreleased/pr-363.v2.yml
  gradle-conjure/src/main/java/com/palantir/gradle/conjure/ConjureJavaLocalCodegenPlugin.java
  gradle-conjure/src/main/java/com/palantir/gradle/conjure/ConjureJavaLocalGeneratorTask.java
  gradle-conjure/src/main/java/com/palantir/gradle/conjure/RenderGeneratorOptions.java
  gradle-conjure/src/main/resources/META-INF/gradle-plugins/com.palantir.conjure-java-local.properties
  gradle-conjure/src/test/groovy/com/palantir/gradle/conjure/ConjureJavaLocalCodegenPluginIntegrationSpec.groovy
  gradle-conjure/src/test/groovy/com/palantir/gradle/conjure/ConjurePluginTest.groovy
  gradle-conjure/src/test/groovy/com/palantir/gradle/conjure/TestVersions.java
  gradle-conjure/src/test/java/com/palantir/gradle/conjure/RenderGeneratorOptionsTest.java
Labels: autorelease, merge when ready

#372 Remove appveyor
  appveyor.yml
Labels: merge when ready, no changelog

#375 Fix issues with conjure-java-local
  changelog/@unreleased/pr-375.v2.yml
  gradle-conjure/src/main/java/com/palantir/gradle/conjure/ConjureJavaLocalCodegenPlugin.java
  gradle-conjure/src/main/java/com/palantir/gradle/conjure/ConjurePlugin.java
  gradle-conjure/src/test/groovy/com/palantir/gradle/conjure/ConjureJavaLocalCodegenPluginIntegrationSpec.groovy
Labels: autorelease, merge when ready

#373 Ignore unused conjure-lib from java subprojects
  changelog/@unreleased/pr-373.v2.yml
  gradle-conjure/src/main/java/com/palantir/gradle/conjure/ConjurePlugin.java
  gradle-conjure/src/test/groovy/com/palantir/gradle/conjure/ConjurePluginTest.groovy
Labels: autorelease, merge when ready

#377 add first class support for dialogue
  build.gradle
  changelog/@unreleased/pr-377.v2.yml
  gradle-conjure/src/main/java/com/palantir/gradle/conjure/ConjurePlugin.java
  gradle-conjure/src/test/groovy/com/palantir/gradle/conjure/ConjurePluginTest.groovy
  gradle-conjure/src/test/groovy/com/palantir/gradle/conjure/TestVersions.java
Labels: autorelease, merge when ready

#381 plumb product dependencies to conjure core
  changelog/@unreleased/pr-381.v2.yml
  gradle-conjure/src/main/java/com/palantir/gradle/conjure/CompileIrTask.java
  gradle-conjure/src/main/java/com/palantir/gradle/conjure/ConjurePlugin.java
  gradle-conjure/src/test/groovy/com/palantir/gradle/conjure/ConjureServiceDependencyTest.groovy
  gradle-conjure/src/test/groovy/com/palantir/gradle/conjure/TestVersions.java
Labels: merge when ready

#385 Inject product dependencies into local generate java projects
  changelog/@unreleased/pr-385.v2.yml
  gradle-conjure/build.gradle
  gradle-conjure/src/main/java/com/palantir/gradle/conjure/ConjureJavaLocalCodegenPlugin.java
  gradle-conjure/src/main/java/com/palantir/gradle/conjure/MinimalConjureDefinition.java
  gradle-conjure/src/test/groovy/com/palantir/gradle/conjure/ConjureJavaLocalCodegenPluginIntegrationSpec.groovy
  versions.lock
  versions.props
Labels: autorelease, merge when ready

#392 ConjureJavaLocalCodegenPlugin: ensure packagePrefix doesn't contain dashes
  changelog/@unreleased/pr-392.v2.yml
  gradle-conjure/src/main/java/com/palantir/gradle/conjure/ConjureJavaLocalCodegenPlugin.java
  gradle-conjure/src/test/groovy/com/palantir/gradle/conjure/ConjureJavaLocalCodegenPluginIntegrationSpec.groovy
Labels: autorelease, merge when ready
