Repository palantir/gradle-conjure, pull requests merged in 2020-03, with the labels that each got.

#393 Configure checkUnusedDependencies by task type
  changelog/@unreleased/pr-393.v2.yml
  gradle-conjure/src/main/java/com/palantir/gradle/conjure/ConjurePlugin.java
Labels: autorelease, merge when ready

#397 Ensure IR is downloaded before configuring pdeps
  changelog/@unreleased/pr-397.v2.yml
  gradle-conjure/src/main/java/com/palantir/gradle/conjure/ConjureJavaLocalCodegenPlugin.java
Labels: autorelease, merge when ready

#398 local codegen works with boms and GCV
  changelog/@unreleased/pr-398.v2.yml
  gradle-conjure/src/main/java/com/palantir/gradle/conjure/ConjureJavaLocalCodegenPlugin.java
Labels: autorelease, merge when ready

#399 Replace javax.annotation-api with jakarta.annoatation-api
  changelog/@unreleased/pr-399.v2.yml
  gradle-conjure/src/main/java/com/palantir/gradle/conjure/ConjurePlugin.java
Labels: autorelease, merge when ready

#412 Lazily configure pdeps
  gradle-conjure/src/main/java/com/palantir/gradle/conjure/ConjureJavaLocalCodegenPlugin.java
  gradle-conjure/src/main/java/com/palantir/gradle/conjure/ConjureJavaServiceDependencies.java
  gradle-conjure/src/main/java/com/palantir/gradle/conjure/ConjurePlugin.java
  gradle-conjure/src/test/groovy/com/palantir/gradle/conjure/ConjureJavaLocalCodegenPluginIntegrationSpec.groovy
  gradle-conjure/src/test/groovy/com/palantir/gradle/conjure/ConjureJavaServiceDependencyProjectSpec.groovy
  gradle-conjure/src/test/groovy/com/palantir/gradle/conjure/ConjureServiceDependencyTest.groovy
Labels: autorelease, merge when ready, no changelog

#417 Produce `rawIr` task
  changelog/@unreleased/pr-417.v2.yml
  gradle-conjure/src/main/java/com/palantir/gradle/conjure/CompileIrTask.java
  gradle-conjure/src/main/java/com/palantir/gradle/conjure/ConjurePlugin.java
  gradle-conjure/src/main/java/com/palantir/gradle/conjure/ConjurePublishPlugin.java
Labels: autorelease, merge when ready

#419 Fix bad advice
  gradle-conjure/src/main/java/com/palantir/gradle/conjure/CompileIrTask.java
Labels: merge when ready, no changelog

#426 Install NPM dependencies with the --no-production flag
  changelog/@unreleased/pr-426.v2.yml
  gradle-conjure/src/main/java/com/palantir/gradle/conjure/ConjurePlugin.java
Labels: autorelease, merge when ready
