Repository palantir/gradle-conjure, pull requests merged in 2020-06, with the labels that each got.

#477 Handle applying gradle-conjure to the root
  changelog/@unreleased/pr-477.v2.yml
  gradle-conjure/src/main/java/com/palantir/gradle/conjure/ConjurePlugin.java
Labels: merge when ready

#478 fix one deprecation warning
  gradle-conjure/src/main/java/com/palantir/gradle/conjure/CompileIrTask.java
Labels: autorelease, merge when ready, no changelog

#479 Delete checkConjureJavaVersions
  gradle-conjure/src/main/java/com/palantir/gradle/conjure/CheckConjureJavaVersions.java
  gradle-conjure/src/main/java/com/palantir/gradle/conjure/ConjurePlugin.java
Labels: merge when ready, no changelog

#480 Remove bad test
  gradle-conjure/src/test/groovy/com/palantir/gradle/conjure/ConjurePluginTest.groovy
Labels: merge when ready, no changelog

#481 remove all deprecation suppressions
  gradle-conjure/src/test/groovy/com/palantir/gradle/conjure/ConjurePluginTest.groovy
  gradle-conjure/src/test/groovy/com/palantir/gradle/conjure/ConjurePublishTest.groovy
  gradle-conjure/src/test/groovy/com/palantir/gradle/conjure/ConjurePublishTypeScriptTest.groovy
Labels: no changelog
